# -*- coding: utf-8 -*-
"""Dashboard Venda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNM4hgjPLNwcuwbMY1JC_h3vZiDyU8mt
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

df = pd.read_excel('/data/faturamento.xlsx')

df.head()

df['ID Loja'] = df['ID Loja'].ffill()

df.head()

from plotly.subplots import make_subplots
import plotly.graph_objects as go

# AGREGAÇÃO (obrigatória)
df_dash = (
    df
    .groupby(['ID Loja', 'Produto'], as_index=False)
    .agg({
        'Quantidade': 'sum',
        'Valor Final': 'sum'
    })
)

# Loja inicial
loja_inicial = df_dash['ID Loja'].unique()[0]
df_init = (
    df_dash[df_dash['ID Loja'] == loja_inicial]
    .sort_values('Produto')
    .reset_index(drop=True)
)

fig = make_subplots(
    rows=2, cols=1,
    subplot_titles=[
        "Quantidade Vendida por Produto",
        "Faturamento por Produto (R$)"
    ],
    vertical_spacing=0.15
)

fig.add_trace(
    go.Bar(
        x=df_init['Produto'].tolist(),
        y=df_init['Quantidade'].tolist(),
        name="Quantidade Vendida",
        marker_color="blue"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_init['Produto'].tolist(),
        y=df_init['Valor Final'].tolist(),
        name="Faturamento (R$)",
        marker_color="red",
        hovertemplate='R$ %{y:,.2f}<extra></extra>'
    ),
    row=2, col=1
)

buttons = []

for loja in df_dash['ID Loja'].unique():
    df_loja = (
        df_dash[df_dash['ID Loja'] == loja]
        .sort_values('Produto')
        .reset_index(drop=True)
    )

    buttons.append(
        dict(
            label=str(loja),
            method="update",
            args=[
                {
                    "x": [df_loja['Produto'].tolist(), df_loja['Produto'].tolist()],
                    "y": [df_loja['Quantidade'].tolist(), df_loja['Valor Final'].tolist()]
                },
                {"title": f"Dashboard de Faturamento - Loja {loja}"}
            ]
        )
    )

fig.update_layout(
    title=f"Dashboard de Faturamento - Loja {loja_inicial}",
    height=1000,
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            x=0.5,
            xanchor="center",
            y=1.12
        )
    ]
)

fig.write_html(
    "index.html",
    include_plotlyjs="cdn",
    full_html=True
)

fig.show()